import { InitMarkdownlintOptions } from 'lint-init-framework';

const ignore = `# Generated by lint-init
node_modules/
build/
coverage/
dist/
`;

export const markdownlint: InitMarkdownlintOptions = {
  deps: {
    'markdownlint-cli': '0.x',
  },
  config: {
    default: true,
  },
  ignore,
  optional: true,
};
