import { InitPrettierOptions } from 'lint-init-framework';

const ignore = `# Generated by lint-init
node_modules/
build/
coverage/
dist/
package-lock.json
pnpm-lock.yaml
yarn.lock
`;

export const prettier: InitPrettierOptions = {
  deps: {
    prettier: '^3.0.0',
    'prettier-plugin-packagejson': '^2.0.0',
  },
  config: {
    plugins: ['prettier-plugin-packagejson'],
  },
  ignore,
};
